### ISSUE TITLE
point cloud in three different planes

### ISSUE THREAD

**Issue by gautamjain1009** [ropod-project/hps_camera#1]
Hi! i am using the driver provided by you for my hypersen solid state lidar for my R&D in Hbrs. I am using the same parameters that you have provided in the hypersen_tests repository in my launch file to run the node. Still i am not able to get the correct point could.

Screenshot of the data visualized in rviz. 
 
![Screenshot from 2019-10-08 15-19-19](https://user-images.githubusercontent.com/37597326/66406306-b4b72a80-e9eb-11e9-93c7-842a5ca47359.png)

Any help would be highly appreciated.

**Comment by PatrickNa** [comment]
From what I remember there was a bigger change in one of the updates of the camera. Now I do not remember if the camera is on a stand after that update and if the driver developed here still applies in its form. I have not looked into it anymore.

Maybe it would be good to bring one of the cameras on the latest stand and update the drivers accordingly. I hope, based on our feedback as well that the company has made major improvements.
