### ISSUE TITLE
How to publish depth image ?

### ISSUE THREAD

**Issue by nyxrobotics** [ropod-project/hps_camera#3]
Anybody knows how to publish depth-image (not pointcloud) ?

**Comment by blumenthal** [comment]
No, not yet - but I  would be interested in that as well. I think @PatrickNa is looking into that.

**Comment by PatrickNa** [comment]
I checked the provided API once more, but could not find any hint regarding this functionality. I then reached out to the author of the HPS3D160 code and ask him about that. Unfortunately he confirmed that there is not functionality in the API that would enable just that.

I asked if they are planning to implement it... Keep you updated when any response arrives.

**Comment by ArthurKetels** [comment]
I guess I am missing something here, but depth image is the default output of the sensor no? Or is this a specific question for the ROS implementation?

Seeing the issues with the point cloud data, I would rather do the calculations myself than relying on the hypersen lib. I would even not use the HDR mode and just output frames with a single sensor integration value and control that value in your own feedback loop. It makes no sense that the camera is doing work for distances you are not interested in at that moment.

**Comment by blumenthal** [comment]
I agree with @ArthurKetels that we should get the RAW depth data and apply our own calculations where necessary. I found in the API both types (depth data and point cloud) can be returned from the SDK:  

https://github.com/ropod-project/hps_camera/blob/master/ros/include/api.h#L405-L407

**Comment by ArthurKetels** [comment]
Perhaps it makes sense to sync with the hypersen github? The files we have are quite old. The new API definition is also translated in English, much easier to read.

https://github.com/hypersen?tab=repositories

**Comment by PatrickNa** [comment]
I'm on it... but the way we implemented the conversion does not work anymore. Thus more than described changed with their update...

**Comment by PatrickNa** [comment]
@nyxrobotics please check b5a626573ee23a78e1b71587d7ad36fe26354d5b on the develop branch.

**Comment by nyxrobotics** [comment]
Thanks a lot. I can see the image on Rviz.
